### ISSUE TITLE
ImportResolveExtension - There was an error during the build of the index.

### ISSUE THREAD

**Issue by abdulkareemnalband** [buehler/typescript-hero#194]
#### System information

- OS: Windows 10 Enterprise Version 1703 build 15063.296
- TypeScript Hero version: 0.13.0
- VSCode version: 1.12.2

#### Description

Whenever I edit a typescript file `Typescript Hero Server` output window takes focus from terminal or whatever other output window i have opened in below panel
with following messages
```
[Error - 2:53:34 PM] undefined
[Error - 3:07:12 PM] undefined
[Error - 3:22:04 PM] undefined
[Error - 3:24:00 PM] undefined
[Error - 3:40:56 PM] undefined
[Error - 3:41:31 PM] undefined
[Error - 3:41:32 PM] undefined
[Error - 3:41:33 PM] undefined
[Error - 3:41:37 PM] undefined

```

##### Steps to reproduce

1. Open any other panel in below panel box say terminal
2. Edit typescript file and save
3.  `Typescript Hero Server` output window takes focus

**Comment by Swiftwork** [comment]
Developer tools logs the following on save:
```batch
[Extension Host] [Error - 13:38:57] DeclarationIndex - Index creation failed, cleanup temp index.
```

**Comment by MickeySegal** [comment]
I see the same behavior as described by abdulkareemnalband.  It started in the past 48 hours, presumably with the 0.13.0 update.  Is there a setting that can turn off this behavior?  the following looks possibly relevant:

  // Defines the log output level in the output window.
  "typescriptHero.verbosity": "Warnings",

but I don't see any documentation of alternative settings so it is difficult to tinker.

Also, a minor annoyance: in the settings.json file, various extensions have sections such as "TSLint" and "BracketPair", while Typescript hero uses "configuration section of the typescript hero extension" which seems verbose and harder to notice than it would be with just "TypeScript Hero".

**Comment by cmaart** [comment]
+1

**Comment by swimmadude66** [comment]
+1 started happening in 0.13.0 update

**Comment by buehler** [comment]
@abdulkareemnalband You can disable the log output with the setting `"typescriptHero.verbosity"` set to "Nothing".

But there seems to be an issue with the creation of the declaration index.

**Comment by buehler** [comment]
Actually, as for the documentation: VSCode does provide you with the possible values of the enum that you can enter into `verbosity`.

**Comment by abdulkareemnalband** [comment]
@buehler I will test this

**Comment by abdulkareemnalband** [comment]
@buehler setting verbosity to nothing
 Makes issue go away 

Thanks for help

But I still think it's just a work around for now

**Comment by buehler** [comment]
I had a bug in the server logger :-(
I corrected it and tried the extension on my windows machine. The error is:

```
[Error - 18:17:52] ImportResolveExtension - There was an error during reprocessing changed files.
	Data:	{ Error: ENOENT: no such file or directory, open 'c:\c%3A\Users\chris\Documents\Development\typescript-hero\src\server\IoC.ts'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at filePathes.map.o (C:\Users\chris\.vscode\extensions\rbbit.typescript-hero-0.13.0\out\src\common\ts-parsing\TypescriptParser.js:24:65)
    at Array.map (native)
    at TypescriptParser.<anonymous> (C:\Users\chris\.vscode\extensions\rbbit.typescript-hero-0.13.0\out\src\common\ts-parsing\TypescriptParser.js:24:18)
    at Generator.next (<anonymous>)
    at C:\Users\chris\.vscode\extensions\rbbit.typescript-hero-0.13.0\node_modules\tslib\tslib.js:96:75
    at Object.__awaiter (C:\Users\chris\.vscode\extensions\rbbit.typescript-hero-0.13.0\node_modules\tslib\tslib.js:92:16)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\c%3A\\Users\\chris\\Documents\\Development\\typescript-hero\\src\\server\\IoC.ts' }
```

**Comment by buehler** [comment]
the error only exists on windows 🙄

**Comment by mceachen** [comment]
> 	Data:	{ Error: ENOENT: no such file or directory, open 'c:\c%3A\Users\chris\Documents\Development\typescript-hero\src\server\IoC.ts'
   
It looks like something is appending a drive letter twice, and urlencoding the second `c:`.

**Comment by buehler** [comment]
Yep somehow :-/

**Comment by alexanderromanov** [comment]
I am getting similar error messages as in original post on OS X as well

**Comment by mceachen** [comment]
Upgraded to 0.13.1, getting 

```
[Error - 10:54:56 AM] ImportResolveExtension - There was an error during the build of the index.
	Data:	TypeError: Cannot read property 'constructor' of undefined
    at TsSerializer.serializeObject ($HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:112:21)
    at $HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (`$HOME`\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)
    at TsSerializer.serializeObject ($HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject ($HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject ($HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at $HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject ($HOME\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)
```

(where $HOME was my user home directory)

**Comment by buehler** [comment]
@mceachen
Which os are you using?

**Comment by mceachen** [comment]
Windows 10 home edition, Version 10.0.15063 Build 15063. vscode 1.12.2, node 7.4.0

**Comment by domoritz** [comment]
@mceachen I have the same issue and reported it at https://github.com/buehler/typescript-hero/issues/200.

**Comment by domoritz** [comment]
I guess you are tracking the issue here. Will close #200.

**Comment by buehler** [comment]
@domoritz @mceachen 
Can you provide some code that is not indexed? I try to reproduce the error, but I don't get the error :-(

**Comment by buehler** [comment]
I'd be very happy if someone with the problem could try out the following branch:
https://github.com/buehler/typescript-hero/tree/fix/error-building-index

I changed the notification system that the server used to send the index to the extension. As well as some null / undefined checks

**Comment by Artfloriani** [comment]
@buehler How can I install an extension from a git branch?

**Comment by buehler** [comment]
@Artfloriani 

Actually, that's pretty easy:

- Check out the repository and the specific branch
- Run `yarn install` or `npm install` in your folder
- Run `yarn run build` or `npm run build`
- Go to `$HOME/.vscode/extensions` folder in your system (so os x / linux -> `~/.vscode/extensions`, and windows -> `C:\Users\<<username>>\.vscode\extensions`)
- Create a symlink to the extension folder (`ln -s ...` or [`mklink /H`](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) on windows)
- Remove or move the original extension (`rbbit-typesript-hero` - ish folder.)
- Run VSCode

**Comment by jamie94bc** [comment]
@buehler I'm still seeing the error after checking out and building that branch.

**Comment by buehler** [comment]
@jamie94bc the one with the constructor of undefined?

**Comment by notVitaliy** [comment]
@buehler 

I was getting a different error on OSX. Seems that it was dropping the leading `/` before `Users`. Checked out the fix branch, error is gone. 👍

**Comment by patrickracicot** [comment]
@buehler I've build the fix branch and I'm still getting the same error.

OS: Windows 10

```
[Error - 9:00:56 AM] ImportResolveExtension - There was an error during the build of the index.
	Data:	TypeError: Cannot read property 'constructor' of undefined
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:112:21)
    at C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (C:\Users\patrick.racicot\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)
```

**Comment by jamie94bc** [comment]
@buehler yes, the same as the @patrickracicot pasted above.

**Comment by swimmadude66** [comment]
Just corroborating here, on v0.13.1 I now get that same error

```
[Error - 11:25:57 AM] ImportResolveExtension - There was an error during the build of the index.
	Data:	TypeError: Cannot read property 'constructor' of undefined
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:112:21)
    at C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:147:49)
    at C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (C:\Users\ayost\.vscode\extensions\rbbit.typescript-hero-0.13.1\node_modules\ts-json-serializer\TsSerializer.js:121:30)

```

**Comment by buehler** [comment]
ok, I upgraded the serializer. Could someone pull and build (with new npm install) the branch and see if the error is still persistent?

**Comment by mceachen** [comment]
```
[Error - 9:34:49 AM] ImportResolveExtension - There was an error during the build of the index.
	Data:	{ Error: Request PartialIndexResult failed with message: Cannot read property '__type' of null
    at new ResponseError (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\messages.js:40:28)
    at handleResponse (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\main.js:305:48)
    at process.callback (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\main.js:486:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
```

**Comment by buehler** [comment]
oh I see...

**Comment by mceachen** [comment]
```
	Data:	{ Error: Request PartialIndexResult failed with message: Cannot read property '__type' of null
    at new ResponseError (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\messages.js:40:28)
    at handleResponse (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\main.js:305:48)
    at process.callback (C:\Users\mrm\.vscode\extensions\typescript-hero\node_modules\vscode-jsonrpc\lib\main.js:486:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: -32603 }
```

**Comment by buehler** [comment]
Well... damn. I'm gonna need to investigate this error further. Are you indexing an angular project? Or what kind of codebase is it?

**Comment by mceachen** [comment]
fails if I open any of my projects, like https://github.com/mceachen/exiftool-vendored.js

**Comment by mceachen** [comment]
Also, while we're here, let me say thanks again for your work on this, it really is great. I wrote a review yesterday: https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero

**Comment by mceachen** [comment]
To verify I'm building a reasonable local build, I just checked out your v0.12.0 tag (fwiw there was a compilation error in `test/provider/ResolveQuickPickProvider.test.ts`, I just deleted it), and functionality (reorder imports, add import) is working properly.

**Comment by buehler** [comment]
@mceachen Thank you :-) Really appreciate it!

It's not making any sense right now. I used your project (exiftool-vendored.js) and don't encounter the errors. When I check in the serializer, the error you experience says it cannot read `constructor of undefined`. This is kind of impossible when I look at the code 😐

**Comment by gund** [comment]
Hi everyone! I'm also experiencing same `constructor of undefined` error on macOS and Windows 10 after an update a few days before...

Just for the reference, trace is pointing to `/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:112:21`.

I'm using it with angular project codebase.

Will try to debug that point and post here the results soon.

**Comment by gund** [comment]
I was trying to debug master branch but could not get breakpoints to stop, not even to stop on exceptions...

The only thing I'm getting in debugger console is this:
`[Error - 13:19:37] DeclarationIndex - Index creation failed, cleanup temp index.`

Also when I'm hitting ctrl-S to save any TS file, in the extension output I got next:
```
[Error - 1:20:31 PM] ImportResolveExtension - There was an error during reprocessing changed files.
	Data:	{ Error: ENOENT: no such file or directory, open 'Users/alexmalkevich/Projects/emaratech/WebFramework/src/em/em.imports.ts'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at tslib_1.__awaiter.filePathes.map.o (/Users/alexmalkevich/Projects/typescript-hero/out/src/common/ts-parsing/TypescriptParser.js:24:65)
    at Array.map (native)
    at TypescriptParser.<anonymous> (/Users/alexmalkevich/Projects/typescript-hero/out/src/common/ts-parsing/TypescriptParser.js:24:18)
    at Generator.next (<anonymous>)
    at __awaiter (/Users/alexmalkevich/Projects/typescript-hero/node_modules/tslib/tslib.js:96:75)
    at Object.__awaiter (/Users/alexmalkevich/Projects/typescript-hero/node_modules/tslib/tslib.js:92:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Users/alexmalkevich/Projects/emaratech/WebFramework/src/em/em.imports.ts' }
```

I was not able to break in TypescriptParser.js nor TypescriptParser.ts (source file)...

**Comment by marcotamburelli** [comment]
Not sure it can help, however I checked TsSerializer.js:
at line 106 it checks if the argument is null,
`        if (obj === null) {`
 then checks for other conditions like
`        else if (obj.constructor === Date) {`
the problem is that if obj is `undefined` (as it seems to happen) it crushes.
I think that it would be better to check the null condition with == or introducing a special case for undefined.

**Comment by swimmadude66** [comment]
@marcotamburelli  that looks promising. Since we need it to be an object, the null check could even be replaced with just a truthiness check to cover null, undefined, and other non-object values.

just change 
```
if (obj === null) {
```
to
```
if (obj) {
```

**Comment by buehler** [comment]
@gund 
yes `ts-json-serializer` is my own (ups..) serializer I wrote: https://github.com/buehler/ts-json-serializer

**Comment by swimmadude66** [comment]
@buehler Slightly off topic, but that project is really cool and I had no idea it existed.

I'm going to try forking that one too and see if that's really the cause.

**Comment by buehler** [comment]
@swimmadude66 Thanks! :-)
I really do appreciate the help! Sometimes it's so random to find an error, and it's a lot of work

**Comment by buehler** [comment]
@gund To actually force vscode to break at a certain point you can use the `debugger;` statement. Then it will definitely stop.

**Comment by buehler** [comment]
@gund @swimmadude66 @mceachen 
Let's have a try off: https://github.com/buehler/typescript-hero/commit/d520798c1ce5e85221a5d47a708ffccd293d948d

(reinstall npm dependencies.)

It should process undefined now, and I found an error with the different platforms (unix vs windows)
```typescript
export function normalizePathUri(uri: string): string {
    const decoded = decodeURIComponent(uri);

    if (platform() === 'win32') {
        return decoded.replace('file:///', '');
    }
    return decoded.replace('file://', '');
}
```

**Comment by swimmadude66** [comment]
@buehler oh man, this isn't even worth me making a PR. You have this fixed already! you just gotta update the dependency on `ts-json-serializer` to ^1.2.0. Just tried it in my fork and the problem is fixed and all tests pass!

**Comment by buehler** [comment]
@swimmadude66 in the fix branch, the dependency should be `1.2.4` right now. I just tried on my windows machine with a normal demo project and an angular project. It seems to be working. Right now testing on os x

**Comment by swimmadude66** [comment]
yeah, I cloned master to try and change as little as possible. That one fix made it work for me on Windows 10. Fingers crossed that it works on OS X as well.

**Comment by buehler** [comment]
Seems to be working. Can somebody confirm it's working?

**Comment by swimmadude66** [comment]
@buehler  I'm gonna get one of my coworkers to test it on their mac, give me a second

**Comment by buehler** [comment]
@swimmadude66 Awesome thanks!
Use the fix branch please :-)

**Comment by gund** [comment]
@buehler just ran in the project on Windows that was throwing an error (not every codebase was throwing that error) and the fix actually fixes the problem!
Great work! Thanks =)

**Comment by swimmadude66** [comment]
@buehler just ran the fix branch on OS X and we got the fabled check mark! you good G!

**Comment by buehler** [comment]
Awesome. :shipit:

**Comment by mceachen** [comment]
Working for me on windows now. Thanks!
