### ISSUE TITLE
ImportResolveExtension - There was an error during the build of the index.

### ISSUE THREAD

**Issue by domoritz** [buehler/typescript-hero#200]
#### System information

- OS: Mac OS
- TypeScript Hero version: 0.13.1
- VSCode version: 1.12.2

#### Description

```
[Error - 7:38:46 PM] ImportResolveExtension - There was an error during the build of the index.
	Data:	TypeError: Cannot read property 'constructor' of undefined
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:112:21)
    at /Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:121:30)
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:147:49)
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:147:49)
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:147:49)
    at /Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:121:62
    at Array.map (native)
    at TsSerializer.serializeObject (/Users/domoritz/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/ts-json-serializer/TsSerializer.js:121:30)
```

##### Steps to reproduce

I just start vscode with some typescript code (github.com/vega/vega-lite).

**Comment by domoritz** [comment]
Tracking in #194
