### ISSUE TITLE
ImportResolveExtension - There was an error during reprocessing changed files

### ISSUE THREAD

**Issue by mosluce** [buehler/typescript-hero#203]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: macOS 10.12.5（16F73）
- TypeScript Hero version: 0.13.1
- VSCode version: 1.12.2

#### Description

```shell
[Error - 上午8:47:08] ImportResolveExtension - There was an error during reprocessing changed files.
	Data:	{ Error: ENOENT: no such file or directory, open 'Users/mosluce/Documents/Workspaces/JS/hero-test/src/app/app.module.ts'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at filePathes.map.o (/Users/mosluce/.vscode/extensions/rbbit.typescript-hero-0.13.1/out/src/common/ts-parsing/TypescriptParser.js:24:65)
    at Array.map (native)
    at TypescriptParser.<anonymous> (/Users/mosluce/.vscode/extensions/rbbit.typescript-hero-0.13.1/out/src/common/ts-parsing/TypescriptParser.js:24:18)
    at Generator.next (<anonymous>)
    at /Users/mosluce/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/tslib/tslib.js:96:75
    at Object.__awaiter (/Users/mosluce/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/tslib/tslib.js:92:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Users/mosluce/Documents/Workspaces/JS/hero-test/src/app/app.module.ts' }

```

##### Steps to reproduce

1. ng new hero-test (angular-cli v1.1.0)
2. cd hero-test
3. code .
4. add space to end of app.module.ts (or any change to the file)
5. the error be shown in output

**Comment by mosluce** [comment]
duplicate #194
