### ISSUE TITLE
Hero outputs "no such file" every time I edit any file and save it.

### ISSUE THREAD

**Issue by idchlife** [buehler/typescript-hero#204]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Mac OS 10.12.5
- TypeScript Hero version: 0.13.1
- VSCode version: 1.12.2

#### Description

Suddenly have error with editing and saving files. Happened maybe after updating something? I can't really tell.

Here is output for hero:

```bash
[Error - 11:18:01 AM] ImportResolveExtension - There was an error during reprocessing changed files.
	Data:	{ Error: ENOENT: no such file or directory, open 'Users/igorandreev/www/own/browser-game/src/server/services/items/weapons/weapon-tools.ts'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at filePathes.map.o (/Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-0.13.1/out/src/common/ts-parsing/TypescriptParser.js:24:65)
    at Array.map (native)
    at TypescriptParser.<anonymous> (/Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-0.13.1/out/src/common/ts-parsing/TypescriptParser.js:24:18)
    at Generator.next (<anonymous>)
    at /Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/tslib/tslib.js:96:75
    at Object.__awaiter (/Users/igorandreev/.vscode/extensions/rbbit.typescript-hero-0.13.1/node_modules/tslib/tslib.js:92:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Users/igorandreev/www/own/browser-game/src/server/services/items/weapons/weapon-tools.ts' }
```

Happens after I edit and save any file (error message always for the file I was editing and saving). Output is bloated with "no such file" errors. Disabling extension, because it's not working now :(

##### Steps to reproduce

Can't really reproduce in quiet serious environment with huge amount of files.

<for feature requests, please use the following template>

#### Feature <name>

<description>

#### Reason

<why it would be cool>

**Comment by philjones88** [comment]
I am getting the same error (bar paths differences).

* OS: Mac OS 10.12.5
* TypeScript Hero version: latest
* VS Code version: insiders latest

**Comment by buehler** [comment]
Yep. this is related to #194 
Will hopefully be fixed asap

**Comment by idchlife** [comment]
Thanks!
