### ISSUE TITLE
ImportResolveExtension error. (Possible yarn workspace issue?)

### ISSUE THREAD

**Issue by quicksnap** [buehler/typescript-hero#284]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Mac OS 10.12.6
- TypeScript Hero version: Latest (1.4.1)
- VSCode version: Latest (1.16.0)

#### Description

When TSH first starts, it indexes fine. But, when I save, I get the following output in the logs:

```
[Error - 14:51:02] ImportResolveExtension - There was an error during the index (re)calculation.
	Data:	TypeError: Cannot read property 'dir' of undefined
	at DeclarationIndex.doesExportResource (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/typescript-parser/DeclarationIndex.js:243:119)
	at Object.keys.forEach (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/typescript-parser/DeclarationIndex.js:219:22)
	at Array.forEach (native)
	at DeclarationIndex.getExportedResources (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/typescript-parser/DeclarationIndex.js:217:14)
	at DeclarationIndex.<anonymous> (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/typescript-parser/DeclarationIndex.js:186:41)
	at Generator.next (<anonymous>)
	at /Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/tslib/tslib.js:96:75
	at Promise (<anonymous>)
	at Object.__awaiter (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/tslib/tslib.js:92:16)
	at DeclarationIndex.reindexForChanges (/Users/danschuman/.vscode/extensions/rbbit.typescript-hero-1.4.1/node_modules/typescript-parser/DeclarationIndex.js:161:24)
```

When I click to manually re-index, it works fine. Upon file save, it errors out again (showing the fire icon).

My project is using yarn workspaces, for what it's worth.

**Comment by buehler** [comment]
Nope, just got those errors too. Maybe they changed something in the extension apis :-/

**Comment by buehler** [comment]
Will have a look at it asap.

**Comment by quicksnap** [comment]
Thanks! Love this extension, btw. It's one of those tools that, once it's not working, I have trouble remembering how I got by without it..

**Comment by asvetliakov** [comment]
I've got the same problem, this PR must fix it (waiting for the new extension build)
https://github.com/TypeScript-Heroes/node-typescript-parser/pull/16

**Comment by buehler** [comment]
@asvetliakov Currently working on it :-)

This is why I really love this community. Thanks for your work!
