### ISSUE TITLE
Ignore Errors in Non JS Based Files

### ISSUE THREAD

**Issue by jfftck** [buehler/typescript-hero#345]
#### System information

- OS: Windows
- TypeScript Hero version: 1.7.0
- VSCode version: 

#### Description

SCSS files throw errors on every change. This extension should only work with files that it understands.

##### Steps to reproduce

1. Open a .scss file.
2. Get a message to view the log file.

##### Expected

1. Should use a white list the files to parse so only the files that should be parsed will be.
2. Or consume the error so the message to view the log file does not display with every change to the file.

**Comment by naeramarth7** [comment]
Example stack trace:

```
2017-11-15T13:51:01.306Z - error: uncaughtException: Import "utils/fonts" could not be resolved.
Error: Import "utils/fonts" could not be resolved.
	at File.load (/Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js:5968:19)
	at /Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js:5974:48
	at FSReqWrap.oncomplete (fs.js:114:15) {"error":{},"stack":"Error: Import \"utils/fonts\" could not be resolved.\n\tat File.load (/Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js:5968:19)\n\tat /Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js:5974:48\n\tat FSReqWrap.oncomplete (fs.js:114:15)","exception":true,"date":"Wed Nov 15 2017 14:51:01 GMT+0100 (CET)","process":{"pid":2090,"uid":26554387,"gid":41305271,"cwd":"/","execPath":"/Users/svenf/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper","version":"v7.9.0","argv":["/Users/svenf/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper","/Users/svenf/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap","--type=extensionHost"],"memoryUsage":{"rss":136364032,"heapTotal":139632640,"heapUsed":124504368,"external":247932}},"os":{"loadavg":[1.53271484375,2.33642578125,2.29150390625],"uptime":21692},"trace":[{"column":19,"file":"/Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js","function":"File.load","line":5968,"method":"load","native":false},{"column":48,"file":"/Users/svenf/.vscode-insiders/extensions/naumovs.color-highlight-2.3.0/dist/extension.js","function":null,"line":5974,"method":null,"native":false},{"column":15,"file":"fs.js","function":"FSReqWrap.oncomplete","line":114,"method":"oncomplete","native":false}]}
```

**Comment by buehler** [comment]
Actually it should ignore non ts / js files.
The stacktrace that was provided by @naeramarth7 does point to another extension (`color-highlight`)

**Comment by naeramarth7** [comment]
@buehler Woah, my bad. Guess I was confused since `color-highlight` did not throw any error when `typescript-hero` was disabled.

However, I could resolve the issue for now by reinstalling `color-highlight`. Thanks for pointing that out.

**Comment by jfftck** [comment]
Why is a bug in another extension being reported in TypeScript Hero?

This should be ignored then.

**Comment by jfftck** [comment]
Since it triggered on every change event and no other extension was reporting this error I would consider this a bug in your logging.

Please fix this as I don't want to be informed when other extensions are throwing exceptions, just TypeScript Hero.

This caused my workflow to interrupted, and since I don't have time to parse the log files to find out that it is an issue with another extension, I disabled TypeScript Hero which then resolved the issue of constant error log notifications.

Could you change how the log message is displayed from a modal dialog to text on the status bar?
