### ISSUE TITLE
 error: uncaughtException: spawn git EMFILE

### ISSUE THREAD

**Issue by hoisel** [buehler/typescript-hero#357]
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Ubuntu
- TypeScript Hero version: 1.7.0
- VSCode version: 1.19.0-insider

#### Description
vscode error alert being repeatedly fired from x in x seconds. The typescript hero log file displays the error below:

##### Steps to reproduce
typescript hero log:

```
2017-12-06T20:45:11.166Z - error: uncaughtException: spawn git EMFILE
Error: spawn git EMFILE
	at exports._errnoException (util.js:1050:11)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9) {"error":{"code":"EMFILE","errno":"EMFILE","syscall":"spawn git","path":"git","spawnargs":["remote","--verbose"]},"stack":"Error: spawn git EMFILE\n\tat exports._errnoException (util.js:1050:11)\n\tat Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n\tat onErrorNT (internal/child_process.js:367:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:80:11)\n\tat process._tickCallback (internal/process/next_tick.js:104:9)","exception":true,"date":"Wed Dec 06 2017 18:45:11 GMT-0200 (-02)","process":{"pid":22717,"uid":1000,"gid":1000,"cwd":"/home/hoisel","execPath":"/usr/share/code-insiders/code-insiders","version":"v7.9.0","argv":["/usr/share/code-insiders/code-insiders","/usr/share/code-insiders/resources/app/out/bootstrap","--type=extensionHost"],"memoryUsage":{"rss":242208768,"heapTotal":190058496,"heapUsed":157383288,"external":3077081}},"os":{"loadavg":[5.63330078125,3.294921875,1.8759765625],"uptime":18996},"trace":[{"column":11,"file":"util.js","function":"exports._errnoException","line":1050,"method":"_errnoException","native":false},{"column":32,"file":"internal/child_process.js","function":"Process.__dirname.ChildProcess._handle.onexit","line":193,"method":"onexit","native":false},{"column":16,"file":"internal/child_process.js","function":"onErrorNT","line":367,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":80,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":104,"method":"_tickCallback","native":false}]}
```

**Comment by buehler** [comment]
This looks like an external error that winston just catched. I disabled the notification since there are other errors in vscode that are catched by winston
