### ISSUE TITLE
Crash with Out of Memory

### ISSUE THREAD

**Issue by Silvenga** [buehler/typescript-hero#363]
#### System information

- OS: Windows 10
- TypeScript Hero version: 1.8.0
- VSCode version: 1.18.1

#### Description

Typescript Hero crashes after opening project with ~2GB RAM used.

```
info: [TypeScriptHero] initialized
...
debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c
<--- Last few GCs --->

[36948:000002651D2B5D30]    83904 ms: Mark-sweep 2052.5 (2134.6) -> 2052.5 (2134.6) MB, 997.6 / 0.0 ms  allocation failure GC in old space requested
[36948:000002651D2B5D30]    84973 ms: Mark-sweep 2052.5 (2134.6) -> 2052.5 (2112.1) MB, 1068.3 / 0.0 ms  last resort 
[36948:000002651D2B5D30]    86107 ms: Mark-sweep 2052.5 (2112.1) -> 2052.5 (2112.1) MB, 1132.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000C477D2B959 <JS Object>
    2: createChildren [C:\Users\User\.vscode\extensions\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~94901] [pc=00000393BE2C095A](this=000002FFE5391909 <a NodeObject with map 0000009E70D20449>,sourceFile=000001F2D3182311 <undefined>)
    3: getChildren [C:\Users\User\.vscode\extensions\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~94957] [pc=...
Extension host terminated unexpectedly. Code:  3  Signal:  null
Extension host terminated unexpectedly.
```

I'm unsure if the following is related:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

##### Steps to reproduce

1.  Clone: https://github.com/Silvenga/silvenga.com
2. Checkout `0807516cd93765bedb5a822a20e5453e1b500df4`
3. Open multi-workspace `./workspace.code-workspace`

**Comment by Inlustra** [comment]
Also getting the same issue running in a multi-workspace project. 

* OS: MacOS High Sierra
* TypeScript Hero version: 1.8.0
* VSCode version: 1.18.1

**Comment by tempit** [comment]
Getting same crash on Ubuntu 16.04, VSCode 1.18.1, TSHero 1.8.0

**Comment by statto1974** [comment]
Also getting same crash

System information

- OS: Windows 10
- TypeScript Hero version: 1.8.0
- VSCode version: 1.18.1

**Comment by Kleyguerth** [comment]
Same crash on openSUSE Tumbleweed, VSCode 1.18.1, TSHero 1.8.0

**Comment by josephhill1** [comment]
Same crash on both Windows 10 Home and Mac OS Sierra
```
[Extension Host] 2017-12-14T18:51:34.815Z - info: [TypeScriptHero] initialized
console.ts:123 [Extension Host] Found all parseable documents.
console.ts:123 [Extension Host] Parsing documents and looking for CSS class definitions...
index.js:41 [uncaught exception]: Error: write EPIPE
onError @ index.js:41
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\init.js:135
i.globals.onerror @ errorTelemetry.ts:64
index.js:44 Error: write EPIPE
    at exports._errnoException (util.js:1050)
    at Socket._writeGeneric (net.js:724)
    at Socket._write (net.js:743)
    at doWrite (_stream_writable.js:329)
    at clearBuffer (_stream_writable.js:436)
    at onwrite (_stream_writable.js:368)
    at WriteWrap.afterWrite [as oncomplete] (net.js:825)
onError @ index.js:44
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ C:\Program Files\Microsoft VS Code\resources\electron.asar\renderer\init.js:135
i.globals.onerror @ errorTelemetry.ts:64
events.js:163 Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1050)
    at Socket._writeGeneric (net.js:724)
    at Socket._write (net.js:743)
    at doWrite (_stream_writable.js:329)
    at clearBuffer (_stream_writable.js:436)
    at onwrite (_stream_writable.js:368)
    at WriteWrap.afterWrite [as oncomplete] (net.js:825)
exports._errnoException @ util.js:1050
Socket._writeGeneric @ net.js:724
Socket._write @ net.js:743
doWrite @ _stream_writable.js:329
clearBuffer @ _stream_writable.js:436
onwrite @ _stream_writable.js:368
afterWrite @ net.js:825
extensionHost.ts:191 [Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c
<--- Last few GCs --->

[18680:000002E00F218B20]   199449 ms: Mark-sweep 2057.3 (2110.5) -> 2057.3 (2110.5) MB, 2928.0 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 5->4
Security context: 0000030E9952B959 <JS Object>
    3: parseErrorAtPosition(aka parseErrorAtPosition) [C:\Users\Josep\.vscode\extensions\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~13521] [pc=00000238D1DED298](this=000003251AC82311 <undefined>,start=2368567,length=0,message=000000E14EC08399 <an Object with map 00000333A80FBAF1>,arg0=000001AC8E351A49 <String[1]: =>)
    4: crea...


extensionService.ts:171 Extension host terminated unexpectedly. Code:  3  Signal:  null
e._onExtensionHostCrashed @ extensionService.ts:171
(anonymous) @ extensionService.ts:144
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
t._onExtHostProcessExit @ extensionHost.ts:416
(anonymous) @ extensionHost.ts:208
emitTwo @ events.js:106
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
messageService.ts:126 Extension host terminated unexpectedly.
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e._onExtensionHostCrashed @ extensionService.ts:178
(anonymous) @ extensionService.ts:144
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
t._onExtHostProcessExit @ extensionHost.ts:416
(anonymous) @ extensionHost.ts:208
emitTwo @ events.js:106
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
```

**Comment by osharper** [comment]
I experience this bug also. since it refers to typescript actually (`\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~13521`) I believe it has to deal something with ts transpilation, so maybe it would worth to refer to this thread about opportunities to fix this https://github.com/Microsoft/TypeScript/issues/14628

the thing to note also: I'm getting this error on meteor+react project, so there is a chance that it has to deal with some recent features introduced
> All the cool stuff for JavaScript as well! (experimental stage though, better description below.)
>   Add imports from javascript files
>   Code outline for JS / JSX files
>   Intellisense for JS / JSX files
_from extension description_

So, maybe there is jsx transpiling to js via `typescript`? :)
I haven't explored codebase yet, will try to do it in some near future. But maybe my observations will be of some help.

At least it would be nice at the moment to introduce setting for disabling those _experimental stage_ features. This should help to localize the issue.

**Comment by oskarols** [comment]
Having the same issue both with quite basic AngularJS project as well as an Angular project.

**Comment by renestalder** [comment]
Same problem. Happens in a basic TypeScript setup without any frameworks.

**Comment by bcarson** [comment]
Me too! I uninstalled VSCode and installed the latest Insider version, same problem. For now I've solved this by disabling TypeScript Hero however I like the extension and would love to see this solved.
- macOS Sierra 10.12.6
- TypeScript Hero 1.8.0
- VSCode 1.20.0-Insider

**Comment by xRuhRohx** [comment]
The only way I have been able to resolve this issue, and it isn't really a fix just a work around and I imagine some people won't be able to do this if they need multiple projects in the workspace, but I just open the folder on the single project I am working on so only one project is open in VSCode. 

OS: Windows 10 Pro Insider Preview
TypeScript Hero: 1.80
VSCode: 1.19.1

**Comment by zephraph** [comment]
Same here on OSX

```

index.js:5 Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
onError @ index.js:5
events.js:163 Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4044 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4044
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744 Extension host terminated unexpectedly.
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2569 [Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: %cnode::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::AbstractCode>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::Factory::SetClassFunctionInstanceDescriptor(v8::internal::Handle<v8::internal::Map>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: v8::internal::Factory::SetClassFunctionInstanceDescriptor(v8::internal::Handle<v8::internal::Map>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: %cv8::internal::CompilationJob::ExecuteJob() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: v8::internal::Compiler::EnsureDeoptimizationSupport(v8::internal::CompilationInfo*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::Compiler::PostInstantiation(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
%c12: v8::internal::Compiler::CompileDebugCode(v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
15: 0x2959a570437d
%c
<--- Last few GCs --->

[51787:0x7f8c8b81f200]    99312 ms: Mark-sweep 2049.4 (2117.0) -> 2049.4 (2114.0) MB, 1884.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1885 ms) last resort 
[51787:0x7f8c8b81f200]   101160 ms: Mark-sweep 2049.4 (2114.0) -> 2049.4 (2114.0) MB, 1847.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24b4f4fab959 <JS Object>
    2: createChildren [/Users/162885/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94901] [pc=0x2959a734cc7a](this=0x2c2291f0d811 <a NodeObject with map 0x31336dbfe2d1>,sourceFile=0x3602ce02311 <undefined>)
    3: getChildren [/Users/162885/.vscode/extensions/rbbit.typescript-hero-1.8.0/node_modules/typescript/lib/typescript.js:~94957] [pc=0x2959a7305...

```

**Comment by mjharper84** [comment]
Same issue for me, started after upgrading to 1.19.1

**Comment by buehler** [comment]
Those problem seem to appear since the multi-root workspaces. I had to refactor some things to make it "kinda" work with the new workspaces. So what I did was basically just instantiate a list of symbols per workspace folder. This could lead to multiple symbols imported the same way. I definitly need to refactor that I suppose.

Or does someone have a good idea on how to handle those multiple workspaces?

This could solve those memory issues, as well as other problems.

Another thing is: parsing a big compiled file (i.e. webpack build result) can lead in a OOM exception since the parser does this recursively. There should be some refactoring done in the parser as well to kill the recursion and make it iterate-able.

**Comment by dougrday** [comment]
I could be wrong, but:

Isn't VS Code already parsing the tree as part of its internal infrastructure?  Otherwise things like "Go to definition" wouldn't work properly.  Are you piggy-backing off that, or did you put in your own AST parser?  If you're using your own parser, it may be beneficial to refactor to piggy-back on what's already happening in VS Code.

**Comment by buehler** [comment]
@dougrday yea I use my own parser.
But maybe I should deactivate the feature for auto imports now since typescript does a pretty good job on its own. This would resolve all those issues.

That way, the extension could focus on other things like organize the imports, and such things.

**Comment by dougrday** [comment]
@buehler Sounds like a good plan to me.  You may consider having a feature toggle for these different features, in case the evolution of TS Hero and VS Code ever conflict like this in the future, one can just turn off the offending feature.

Maybe something in settings.json?

**Comment by buehler** [comment]
@dougrday that actually sounds like a plan.

**Comment by fbartho** [comment]
@buehler The default TypeScript importer always gives me root-relative import paths (which then don't work with both Webpack & Babel at the same time), so I was definitely appreciating your importer while it worked.

Sadly, I'm also exhibiting this crash.

**Comment by smasala** [comment]
+1

**Comment by briancvn** [comment]
Also getting same crash
System information
OS: Windows 10
TypeScript Hero version: 1.8.0
VSCode version: 1.20.0-insider

**Comment by shairez** [comment]
Found this comment on #331 which helped me in the meantime - 

https://github.com/buehler/typescript-hero/issues/331#issuecomment-342176190

**Comment by buehler** [comment]
I'm on it :-)
https://github.com/buehler/typescript-hero/tree/refactor/application

I'm gonna release 2.0.0 as soon as I finished the last bits (testing)

The breaking change will be, that there will be no more pre parsing and autocomplete. I'm gonna use the autocomplete of vscode for starters (to make the extension work again). And THEN I can add back those features

**Comment by jscti** [comment]
@buehler Still having this same crash on 2.1.1 @vscode1.19.3@MacOS10.13.2
